version: '3.1'
services:
    mysql:
        container_name: React-Golang_JWT_Authentication
        image: 'mysql:8.0'
        environment:
            - MYSQL_USER=admin
            - MYSQL_PASSWORD=admin
            - MYSQL_ROOT_PASSWORD=admin
            - MYSQL_DATABASE=yt_go_auth
        ports:
            # - '3307:3306'
            - '3306:3306'

### STEP 1 ###
# docker exec -it <CONTAINER_ID>  mysql -uroot -p
# Enter password:MYSQL_DATABASE

### STEP 2 ###
# mysql>  CREATE USER 'http'@'172.23.0.1' IDENTIFIED BY 'http';
# mysql> GRANT ALL PRIVILEGES ON *.* TO 'http'@'172.23.0.1' WITH GRANT OPTION;
# mysql> flush privileges; 
# mysql> exit
