version: '3.1'
services:
    mysql:
        container_name: DATABASE_ACCESS
        image: 'mysql:8.0'
        environment:
            - MYSQL_USER=access
            - MYSQL_PASSWORD=access
            - MYSQL_ROOT_PASSWORD=MYSQL_DATABASE
            - MYSQL_DATABASE=ACCESS
        ports:
            - '8002:3306'
